apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-k8s
spec:
  selector:
    matchLabels:
      app: backend-k8s
  template:
    metadata:
      labels:
        app: backend-k8s
    spec:
      containers:
      - name: backend-k8s
        image: backend-k8s
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
        imagePullPolicy: IfNotPresent
