apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-k8s
spec:
  selector:
    matchLabels:
      app: frontend-k8s
  template:
    metadata:
      labels:
        app: frontend-k8s
    spec:
      containers:
      - name: frontend-k8s
        image: frontend-k8s
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        imagePullPolicy: IfNotPresent
